config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/about' => 'static_pages#about', as: 'about'

  get '/welcome' => 'static_pages#welcome', as: 'welcome'

  root 'static_pages#home'

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }
  
  resources :genres

  resources :artists

  resources :songs

  resources :albums

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	belongs_to :genre
	has_many :albums
	has_many :songs

	validates :name, presence: true
	validates :name, uniqueness: true
	validates :name, length: {minimum: 3}
	validates :bio, length: {maximum: 1000}

	extend FriendlyId
  	friendly_id :name, use: :slugged
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
    @genres = Genre.all 
  end

  # GET /artists/1/edit
  def edit
    @genres = Genre.all 
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :bio, :genre_id)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= bootstrap_form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.collection_select :genre_id, @genres, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <!-- Shows "no bio" if the field is empty -->
        <td><%= artist.bio.presence || "No Bio" %></td>
        <td><%= artist.genre.name %></td>
        <td><%= link_to 'Show', artist %> | <%= link_to 'Edit', edit_artist_path(artist) %> | <%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path, class: "btn btn-default" %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p>
<b>Albums by this Artist:</b>
<ul>
<% @artist.albums.each do |album| %>
<li><%= album.title %></li>
<% end %>
</ul>
</p>