config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/about' => 'static_pages#about', as: 'about'

  get '/welcome' => 'static_pages#welcome', as: 'welcome'

  root 'static_pages#home'

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }
  
  resources :genres

  resources :artists

  resources :songs

  resources :albums

end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :genre
	belongs_to :artist
	belongs_to :album

	validates :name, presence: true

	extend FriendlyId
  	friendly_id :name, use: :slugged
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  include SongsHelper
  # GET /songs
  # GET /songs.json

  def index
    @songs = Song.paginate(page: params[:page], per_page: 20)
    
    # if params[:query]
    #   @songs = Song.where(name: params[:query].titleize)
    # else
    #   @songs = Song.all
    # end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    songs_and_tracks
  end

  # GET /songs/new
  def new
    @song = Song.new
    @genres = Genre.all
    @artists = Artist.all
    @albums = Album.all 
  end

  # GET /songs/1/edit
  def edit
    @genres = Genre.all
    @artists = Artist.all
    @albums = Album.all 
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :genre_id, :artist_id, :album_id)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
	def songs_and_tracks
		require 'grooveshark'
	    client = Grooveshark::Client.new
	    songs = client.search_songs("#{@song.artist.name} #{@song.name} #{@song.album.title}")

	    @track = songs.first

	    require 'musix_match'
	    MusixMatch::API::Base.api_key = ENV['musixmatch']
	    response = MusixMatch.search_track(q: "#{@song.artist.name} #{@song.name}")
	    if response.status_code == 200
	      response.each do |track|
	        @lyric_id = track.track_id
	      end
	    end

	    lyric_response = MusixMatch.get_lyrics(@lyric_id)
	    if lyric_response.status_code == 200 && lyrics = lyric_response.lyrics
	      @lyrics = lyrics.lyrics_body
	    end
	end
end

app/views/songs/_form.html.erb
<%= bootstrap_form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.collection_select :genre_id, @genres, :id, :name %>
  </div>
  <div class="field">
    <%= f.collection_select :artist_id, @artists, :id, :name %>
  </div>
  <div class="field">
    <%= f.collection_select :album_id, @albums, :id, :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Search Songs:</h1>
<div>
  <%= form_tag("/songs", method: "get") do %>
    <%= label_tag(:query, "Song Title:") %>
    <%= text_field_tag(:query) %>
    <%= submit_tag("Find Song") %>
  <% end %>
</div>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Genre</th>
      <th>Artist</th>
      <th>Album</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.genre.name %></td>
        <td><%= song.artist.name %></td>
        <td><%= song.album.title %></td>
        <td><%= link_to 'Show', song %> | <%= link_to 'Edit', edit_song_path(song) %> | <%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path, class: "btn btn-default" %>

<%= will_paginate @songs, renderer: BootstrapPagination::Rails %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @song.genre.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist.name %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album.title %>
</p>

<% if @track != nil %>
	<object width="250" height="40" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="gsSong<%= @track.id %>" name="gsSong<%= @track.id %>"><param name="movie" value="http://grooveshark.com/songWidget.swf" /><param name="wmode" value="window" /><param name="allowScriptAccess" value="always" /><param name="flashvars" value="hostname=grooveshark.com&songID=<%= @track.id %>&style=metal&p=0" /><object type="application/x-shockwave-flash" data="http://grooveshark.com/songWidget.swf" width="250" height="40"><param name="wmode" value="window" /><param name="allowScriptAccess" value="always" /><param name="flashvars" value="hostname=grooveshark.com&songID=<%= @track.id %>&style=metal&p=0" /><span></span></object></object>
<% else %>
	<p>This track does not exist.</p>
<% end %>
<br>
<%= @lyrics %>

<br>
<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>

<p>Song audio powered by <a href="http://www.grooveshark.com/">Grooveshark</a> | Song lyrics powered by <a href="https://www.musixmatch.com">Musixmatch</a></p>