config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/about' => 'static_pages#about', as: 'about'

  get '/welcome' => 'static_pages#welcome', as: 'welcome'

  root 'static_pages#home'

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }
  
  resources :genres

  resources :artists

  resources :songs

  resources :albums

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>MusicDB</title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Arimo:400,700|Lobster' rel='stylesheet' type='text/css'>

</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
	  	<div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    	<div class="navbar-header">
	      		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        		<span class="sr-only">Toggle navigation</span>
	        		<span class="icon-bar"></span>
	        		<span class="icon-bar"></span>
	        		<span class="icon-bar"></span>
	      		</button>
	      		<a class="navbar-brand">MusicDB</a>
	    	</div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      	<ul class="nav navbar-nav">
	        	<li><%= link_to "Genres", genres_path %></li>
	        	<li><%= link_to "Artists", artists_path %></li>
	        	<li><%= link_to "Albums", albums_path %></li>
	        	<li><%= link_to "Songs", songs_path %></li>
	      	</ul>
<!-- 	      	<form class="navbar-form navbar-left" role="search">
        		<div class="form-group">
          			<input type="text" class="form-control" placeholder="Search Songs">
        		</div>
        		<button type="submit" class="btn btn-default">Submit</button>
      		</form> -->
	      	<ul class="nav navbar-nav navbar-right">
	        	<li><%= link_to "About", about_path %></li>
	        	<li><%= link_to "Home", root_path %></li>
	      	</ul>
	    </div><!-- /.navbar-collapse -->
	  	</div><!-- /.container-fluid -->
	</nav>

	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  	<div class="sign_up"><p>
    	<% if user_signed_in? %>
    		Logged in as <strong><%= current_user.email %></strong> | 
    		<%= link_to "Edit Profile", edit_user_registration_path, class: "navbar-link" %> | 
    		<%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link" %>
    	<% else %>
    		<%= link_to "Sign Up", new_user_registration_path, class: "navbar-link" %> | 
    		<%= link_to "Login", new_user_session_path, class: "navbar-link" %>
    	<% end %>
    </p></div>

    <%= yield %>
  	</div>
</body>
</html>